"""add audit_log

Revision ID: 2233f0ac16f0
Revises: 5436d25c3bed
Create Date: 2026-03-24 09:25:28.444052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2233f0ac16f0'
down_revision: Union[str, Sequence[str], None] = '5436d25c3bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'QUOTATION', 'WIN', 'LOST', 'CANCELLED', 'SUPERSEDED', name='quotationstatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_quotations_quotation_no'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quotation_no'), 'quotations', ['quotation_no'], unique=False)
    op.create_index('idx_quotation_no_version_deleted', 'quotations', ['quotation_no', 'version', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_quotations_deleted_at'), 'quotations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index(op.f('ix_quotations_version'), 'quotations', ['version'], unique=False)
    op.create_unique_constraint('uq_quotation_no_version', 'quotations', ['quotation_no', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quotation_no_version', 'quotations', type_='unique')
    op.drop_index(op.f('ix_quotations_version'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_deleted_at'), table_name='quotations')
    op.drop_index('idx_quotation_no_version_deleted', table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_no'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quotation_no'), 'quotations', ['quotation_no'], unique=True)
    op.alter_column('quotations', 'status',
               existing_type=sa.Enum('DRAFT', 'QUOTATION', 'WIN', 'LOST', 'CANCELLED', 'SUPERSEDED', name='quotationstatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
