"""quotation soft delete

Revision ID: 41d8fee041fb
Revises: b13888e7e81a
Create Date: 2026-03-25 14:23:08.456291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d8fee041fb'
down_revision: Union[str, Sequence[str], None] = 'b13888e7e81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_attachments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('quotation_item_images', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_item_images', 'deleted_at')
    op.drop_column('quotation_attachments', 'deleted_at')
    # ### end Alembic commands ###
