"""create company

Revision ID: 55f4f6cd2548
Revises: 9902a99bab5a
Create Date: 2026-04-01 03:11:23.218726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f4f6cd2548'
down_revision: Union[str, Sequence[str], None] = '9902a99bab5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('code_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_code_number'), 'companies', ['code_number'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=False)
    op.create_index(op.f('ix_companies_trcloud_id'), 'companies', ['trcloud_id'], unique=True)
    op.create_table('company_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_contacts'))
    )
    op.create_index(op.f('ix_company_contacts_contact_id'), 'company_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_company_contacts_id'), 'company_contacts', ['id'], unique=False)
    op.add_column('quotations', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('quotations', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_quotations_company_id_companies'), 'quotations', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('fk_quotations_contact_id_company_contacts'), 'quotations', 'company_contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quotations_contact_id_company_contacts'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_company_id_companies'), 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'contact_id')
    op.drop_column('quotations', 'company_id')
    op.drop_index(op.f('ix_company_contacts_id'), table_name='company_contacts')
    op.drop_index(op.f('ix_company_contacts_contact_id'), table_name='company_contacts')
    op.drop_table('company_contacts')
    op.drop_index(op.f('ix_companies_trcloud_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_code_number'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
