"""add product master and trcloud integration tables

Revision ID: 9902a99bab5a
Revises: e4fe28d4ee64
Create Date: 2026-03-26 16:52:12.718096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9902a99bab5a'
down_revision: Union[str, Sequence[str], None] = 'e4fe28d4ee64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_logs'))
    )
    op.create_index(op.f('ix_webhook_logs_action'), 'webhook_logs', ['action'], unique=False)
    op.create_index(op.f('ix_webhook_logs_engine'), 'webhook_logs', ['engine'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_table('tr_sale_orders',
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_tr_sale_orders_quotation_id_quotations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_sale_orders'))
    )
    op.create_index(op.f('ix_tr_sale_orders_company_format'), 'tr_sale_orders', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_sale_orders_document_number'), 'tr_sale_orders', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_sale_orders_id'), 'tr_sale_orders', ['id'], unique=False)
    op.create_index(op.f('ix_tr_sale_orders_trcloud_id'), 'tr_sale_orders', ['trcloud_id'], unique=True)
    op.create_table('tr_invoices',
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_tr_invoices_quotation_id_quotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['so_id'], ['tr_sale_orders.id'], name=op.f('fk_tr_invoices_so_id_tr_sale_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_invoices'))
    )
    op.create_index(op.f('ix_tr_invoices_company_format'), 'tr_invoices', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_invoices_document_number'), 'tr_invoices', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_invoices_id'), 'tr_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_tr_invoices_trcloud_id'), 'tr_invoices', ['trcloud_id'], unique=True)
    op.create_table('tr_material_requests',
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['so_id'], ['tr_sale_orders.id'], name=op.f('fk_tr_material_requests_so_id_tr_sale_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_material_requests'))
    )
    op.create_index(op.f('ix_tr_material_requests_company_format'), 'tr_material_requests', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_material_requests_document_number'), 'tr_material_requests', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_material_requests_id'), 'tr_material_requests', ['id'], unique=False)
    op.create_index(op.f('ix_tr_material_requests_trcloud_id'), 'tr_material_requests', ['trcloud_id'], unique=True)
    op.create_table('tr_purchase_requests',
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['so_id'], ['tr_sale_orders.id'], name=op.f('fk_tr_purchase_requests_so_id_tr_sale_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_purchase_requests'))
    )
    op.create_index(op.f('ix_tr_purchase_requests_company_format'), 'tr_purchase_requests', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_purchase_requests_document_number'), 'tr_purchase_requests', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_purchase_requests_id'), 'tr_purchase_requests', ['id'], unique=False)
    op.create_index(op.f('ix_tr_purchase_requests_trcloud_id'), 'tr_purchase_requests', ['trcloud_id'], unique=True)
    op.create_table('tr_purchase_orders',
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['tr_purchase_requests.id'], name=op.f('fk_tr_purchase_orders_pr_id_tr_purchase_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['so_id'], ['tr_sale_orders.id'], name=op.f('fk_tr_purchase_orders_so_id_tr_sale_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_purchase_orders'))
    )
    op.create_index(op.f('ix_tr_purchase_orders_company_format'), 'tr_purchase_orders', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_purchase_orders_document_number'), 'tr_purchase_orders', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_purchase_orders_id'), 'tr_purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_tr_purchase_orders_trcloud_id'), 'tr_purchase_orders', ['trcloud_id'], unique=True)
    op.create_table('tr_good_receives',
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trcloud_id', sa.String(length=100), nullable=True),
    sa.Column('company_format', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('head', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['tr_purchase_orders.id'], name=op.f('fk_tr_good_receives_po_id_tr_purchase_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_good_receives'))
    )
    op.create_index(op.f('ix_tr_good_receives_company_format'), 'tr_good_receives', ['company_format'], unique=False)
    op.create_index(op.f('ix_tr_good_receives_document_number'), 'tr_good_receives', ['document_number'], unique=False)
    op.create_index(op.f('ix_tr_good_receives_id'), 'tr_good_receives', ['id'], unique=False)
    op.create_index(op.f('ix_tr_good_receives_trcloud_id'), 'tr_good_receives', ['trcloud_id'], unique=True)
    op.add_column('quotations', sa.Column('external_qo_id', sa.String(length=100), nullable=True))
    op.add_column('quotations', sa.Column('external_qo_no', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('external_so_no', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('external_inv_no', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('external_system_status', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('external_last_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('linked_trcloud_so_id', sa.String(length=100), nullable=True))
    op.add_column('quotations', sa.Column('linked_trcloud_so_no', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('sync_status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_quotations_external_inv_no'), 'quotations', ['external_inv_no'], unique=False)
    op.create_index(op.f('ix_quotations_external_qo_id'), 'quotations', ['external_qo_id'], unique=False)
    op.create_index(op.f('ix_quotations_external_qo_no'), 'quotations', ['external_qo_no'], unique=False)
    op.create_index(op.f('ix_quotations_external_so_no'), 'quotations', ['external_so_no'], unique=False)
    op.create_index(op.f('ix_quotations_linked_trcloud_so_id'), 'quotations', ['linked_trcloud_so_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_linked_trcloud_so_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_external_so_no'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_external_qo_no'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_external_qo_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_external_inv_no'), table_name='quotations')
    op.drop_column('quotations', 'sync_status')
    op.drop_column('quotations', 'linked_trcloud_so_no')
    op.drop_column('quotations', 'linked_trcloud_so_id')
    op.drop_column('quotations', 'external_last_update')
    op.drop_column('quotations', 'external_system_status')
    op.drop_column('quotations', 'external_inv_no')
    op.drop_column('quotations', 'external_so_no')
    op.drop_column('quotations', 'external_qo_no')
    op.drop_column('quotations', 'external_qo_id')
    op.drop_index(op.f('ix_tr_good_receives_trcloud_id'), table_name='tr_good_receives')
    op.drop_index(op.f('ix_tr_good_receives_id'), table_name='tr_good_receives')
    op.drop_index(op.f('ix_tr_good_receives_document_number'), table_name='tr_good_receives')
    op.drop_index(op.f('ix_tr_good_receives_company_format'), table_name='tr_good_receives')
    op.drop_table('tr_good_receives')
    op.drop_index(op.f('ix_tr_purchase_orders_trcloud_id'), table_name='tr_purchase_orders')
    op.drop_index(op.f('ix_tr_purchase_orders_id'), table_name='tr_purchase_orders')
    op.drop_index(op.f('ix_tr_purchase_orders_document_number'), table_name='tr_purchase_orders')
    op.drop_index(op.f('ix_tr_purchase_orders_company_format'), table_name='tr_purchase_orders')
    op.drop_table('tr_purchase_orders')
    op.drop_index(op.f('ix_tr_purchase_requests_trcloud_id'), table_name='tr_purchase_requests')
    op.drop_index(op.f('ix_tr_purchase_requests_id'), table_name='tr_purchase_requests')
    op.drop_index(op.f('ix_tr_purchase_requests_document_number'), table_name='tr_purchase_requests')
    op.drop_index(op.f('ix_tr_purchase_requests_company_format'), table_name='tr_purchase_requests')
    op.drop_table('tr_purchase_requests')
    op.drop_index(op.f('ix_tr_material_requests_trcloud_id'), table_name='tr_material_requests')
    op.drop_index(op.f('ix_tr_material_requests_id'), table_name='tr_material_requests')
    op.drop_index(op.f('ix_tr_material_requests_document_number'), table_name='tr_material_requests')
    op.drop_index(op.f('ix_tr_material_requests_company_format'), table_name='tr_material_requests')
    op.drop_table('tr_material_requests')
    op.drop_index(op.f('ix_tr_invoices_trcloud_id'), table_name='tr_invoices')
    op.drop_index(op.f('ix_tr_invoices_id'), table_name='tr_invoices')
    op.drop_index(op.f('ix_tr_invoices_document_number'), table_name='tr_invoices')
    op.drop_index(op.f('ix_tr_invoices_company_format'), table_name='tr_invoices')
    op.drop_table('tr_invoices')
    op.drop_index(op.f('ix_tr_sale_orders_trcloud_id'), table_name='tr_sale_orders')
    op.drop_index(op.f('ix_tr_sale_orders_id'), table_name='tr_sale_orders')
    op.drop_index(op.f('ix_tr_sale_orders_document_number'), table_name='tr_sale_orders')
    op.drop_index(op.f('ix_tr_sale_orders_company_format'), table_name='tr_sale_orders')
    op.drop_table('tr_sale_orders')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_engine'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_action'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
