"""quotation attachment

Revision ID: b13888e7e81a
Revises: 6ce9b794551c
Create Date: 2026-03-25 10:56:03.721573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13888e7e81a'
down_revision: Union[str, Sequence[str], None] = '6ce9b794551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_attachments_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_attachments'))
    )
    op.create_index(op.f('ix_quotation_attachments_id'), 'quotation_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_attachments_quotation_id'), 'quotation_attachments', ['quotation_id'], unique=False)
    op.create_table('quotation_item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['quotation_items.id'], name=op.f('fk_quotation_item_images_item_id_quotation_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_item_images'))
    )
    op.create_index(op.f('ix_quotation_item_images_id'), 'quotation_item_images', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_item_images_item_id'), 'quotation_item_images', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_item_images_item_id'), table_name='quotation_item_images')
    op.drop_index(op.f('ix_quotation_item_images_id'), table_name='quotation_item_images')
    op.drop_table('quotation_item_images')
    op.drop_index(op.f('ix_quotation_attachments_quotation_id'), table_name='quotation_attachments')
    op.drop_index(op.f('ix_quotation_attachments_id'), table_name='quotation_attachments')
    op.drop_table('quotation_attachments')
    # ### end Alembic commands ###
