"""addquotation note env

Revision ID: e224a2be29b6
Revises: 2ed18cf181e4
Create Date: 2026-03-24 15:38:22.412179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e224a2be29b6'
down_revision: Union[str, Sequence[str], None] = '2ed18cf181e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_notes_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_notes'))
    )
    op.create_index(op.f('ix_quotation_notes_id'), 'quotation_notes', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_notes_quotation_id'), 'quotation_notes', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_notes_quotation_id'), table_name='quotation_notes')
    op.drop_index(op.f('ix_quotation_notes_id'), table_name='quotation_notes')
    op.drop_table('quotation_notes')
    # ### end Alembic commands ###
